### ISSUE TITLE
New Pymatgen change slightly breaks scripts

### ISSUE THREAD

**Issue by adenchfi** [comscope/Comsuite#1]
Hi, 
According to [their home page](https://pymatgen.org/), pymatgen has introduced some compatibility changes in 2022. One of which is changing where some of their root info is put.

In flapwmbpt_ini.py, line 22, 
`versionstr = '%(prog)s version 0.0\npymatgen version '+mg.__version__`
this will not work with recent pymatgen changes, instead crashing with 
`AttributeError: module 'pymatgen' has no attribute '__version__'`

Instead, one must use
`import pymatgen.core as pcore`
`versionstr = '%(prog)s version 0.0\npymatgen version '+pcore.__version__`

EDIT: It appears there are more breaking changes with the new pymatgen structure. Or perhaps I am missing something :) 

I don't know how you may want to change the code to account for both versions, since well, querying the version itself has changed.

**Comment by sangkookchoi** [comment]
Hi, we appreciate your report. For now, we will disable lines related to pymatgen version, which are not essential for the python script.

**Comment by sangkookchoi** [comment]
Check the master branch:)

**Comment by adenchfi** [comment]
As I mentioned, there are other issues (that I lazily did not document) with the newer pymatgen versions in Comsuite.
Doing python3 $COMSUITE_BIN/comdmft.py on a dft tutorial file, I get
![image](https://user-images.githubusercontent.com/10607496/165888488-a5da9f23-b926-4fed-a167-3369dac93038.png)
This is with pymatgen 2022.0.17. However, downgrading to pymatgen 2021.3.4 yields a successful completion. 
NOTE: Due to the other issue I brought up, I am currently using the Comscope2021SummerSchool branch, as it compiles and runs for me.

**Comment by vsacksteder** [comment]
Hi Adam, how is comsuite working for you now?  Are you still having the same problems, or have your worked around them by going to the summer school branch? Best, Vincent
